# Generated by Django 3.0.7 on 2024-10-09 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_notification_notificationmsgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmsgs',
            name='msg_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
