# Generated by Django 3.0.7 on 2024-10-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_notificationmsgs_msg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmedia',
            name='media',
            field=models.FileField(upload_to='posts/'),
        ),
    ]
