# Generated by Django 3.0.7 on 2024-10-19 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmsgs',
            name='for_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forpost', to='App.Posts'),
        ),
        migrations.AddField(
            model_name='notificationmsgs',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fromuser', to='App.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='backupimage',
            field=models.ImageField(null=True, upload_to='searches/'),
        ),
    ]
