# Generated by Django 5.1.3 on 2024-11-30 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatUsers', models.ManyToManyField(blank=True, related_name='userchats', to='App.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatuser', to='App.user')),
            ],
        ),
    ]
